In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
model = LinearRegression()

In [3]:
employment_df = pd.read_csv('employment_clean.csv')
employment_df

FileNotFoundError: [Errno 2] File employment_clean.csv does not exist: 'employment_clean.csv'

In [5]:
df_2019 = employment_df['2019'].copy()
df_2019

0      107405
1      433800
2       83286
3       64277
4      579135
        ...
379    136556
380    243152
381    283700
382     75581
383     91296
Name: 2019, Length: 384, dtype: int64

In [7]:

employment_df.drop(columns = ['2019'])

,GeoFips,GeoName,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,10180,"Abilene, TX (Metropolitan Statistical Area)",89511,90338,91132,91998,92937,94097,96484,99264,97269,96809,98193,99843,101199,102316,102611,102601,102786,104536
1,10420,"Akron, OH (Metropolitan Statistical Area)",396954,396663,396391,404591,412097,417595,424012,424079,404521,402554,407811,412049,414502,421225,426047,427394,428034,430261
2,10500,"Albany, GA (Metropolitan Statistical Area)",78011,77100,78282,78126,80177,80621,81153,80663,78714,77793,79189,79388,79694,80577,81418,81714,81872,82431
3,10540,"Albany-Lebanon, OR (Metropolitan Statistical A...",54749,54136,53710,54697,57088,58162,59546,59473,56122,55562,55341,55676,56161,57670,58997,59661,61777,63422
4,10580,"Albany-Schenectady-Troy, NY (Metropolitan Stat...",516432,514437,518106,524002,530740,534257,540904,543929,535314,528095,531541,537634,543162,548362,556276,563056,569909,575772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,49420,"Yakima, WA (Metropolitan Statistical Area)",112685,112734,114189,113223,114927,117779,118536,121722,120007,119123,120041,124847,125387,127305,128600,130601,132743,134982
380,49620,"York-Hanover, PA (Metropolitan Statistical Area)",211514,211138,211658,217006,223488,226836,231790,232142,223008,221987,224717,225936,227264,229563,231735,235643,237721,240494
381,49660,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",311150,305452,302591,301803,303520,302814,301433,295953,280869,280982,285225,287302,287503,287915,287937,288202,284315,284853
382,49700,"Yuba City, CA (Metropolitan Statistical Area)",61499,62404,62573,63898,64648,66167,67736,65442,63426,62526,62563,63966,65465,66816,68645,69903,71388,73096
383,49740,"Yuma, AZ (Metropolitan Statistical Area)",70656,72784,74549,78518,80808,83776,85115,83665,79960,79901,80988,82389,83070,83664,85800,88674,88293,89875

In [8]:
predictions = []
for i in range(0,384):
    x = [[2002],[2003],[2004],[2005],[2006],[2007],[2008],[2009],[2010],[2011],[2012],[2013],[2014],[2015],[2016],[2017],[2018]]
    y = employment_df.iloc[i, 2:].values
    model.fit(x,y)
    y_pred = model.predict([[2019]])
    predictions.append(y_pred)
flat_list = [item for sublist in predictions for item in sublist]
employment_df['prediction_2019'] = flat_list
employment_df

ValueError: Found input variables with inconsistent numbers of samples: [17, 19]

In [6]:
employment_df.to_csv('employment_prediction_2019.csv')

In [9]:
df = employment_df[['GeoFips','GeoName','prediction_2019']].copy()
df

,GeoFips,GeoName,prediction_2024
0,10180,"Abilene, TX (Metropolitan Statistical Area)",1.144664
1,10420,"Akron, OH (Metropolitan Statistical Area)",0.542719
2,10500,"Albany, GA (Metropolitan Statistical Area)",0.766707
3,10540,"Albany-Lebanon, OR (Metropolitan Statistical A...",2.458366
4,10580,"Albany-Schenectady-Troy, NY (Metropolitan Stat...",1.186648
...,...,...,...
379,49420,"Yakima, WA (Metropolitan Statistical Area)",1.880975
380,49620,"York-Hanover, PA (Metropolitan Statistical Area)",0.844262
381,49660,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",0.284994
382,49700,"Yuba City, CA (Metropolitan Statistical Area)",2.833319
383,49740,"Yuma, AZ (Metropolitan Statistical Area)",0.236894

In [10]:
df['employment_prediction_2024_rank']=df['prediction_2024'].rank(method='max')
df

,GeoFips,GeoName,prediction_2024,employment_prediction_2024_rank
0,10180,"Abilene, TX (Metropolitan Statistical Area)",1.144664,177.0
1,10420,"Akron, OH (Metropolitan Statistical Area)",0.542719,108.0
2,10500,"Albany, GA (Metropolitan Statistical Area)",0.766707,130.0
3,10540,"Albany-Lebanon, OR (Metropolitan Statistical A...",2.458366,305.0
4,10580,"Albany-Schenectady-Troy, NY (Metropolitan Stat...",1.186648,182.0
...,...,...,...,...
379,49420,"Yakima, WA (Metropolitan Statistical Area)",1.880975,253.0
380,49620,"York-Hanover, PA (Metropolitan Statistical Area)",0.844262,145.0
381,49660,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",0.284994,77.0
382,49700,"Yuba City, CA (Metropolitan Statistical Area)",2.833319,326.0
383,49740,"Yuma, AZ (Metropolitan Statistical Area)",0.236894,74.0

In [12]:
df.to_csv('employment_prediction_2014v2.csv')