In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
model = LinearRegression()

In [3]:
employment_df = pd.read_csv('employment_MSA_clean.csv')
employment_df

,GeoFips,GeoName,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,10180,"Abilene, TX (Metropolitan Statistical Area)",0.923909,0.878921,0.950270,1.020674,1.248157,2.536744,2.881307,-2.009792,-0.472915,1.429619,1.680364,1.358132,1.103766,0.288322,-0.009746,0.180310,1.702566,2.744509
1,10420,"Akron, OH (Metropolitan Statistical Area)",-0.073308,-0.068572,2.068665,1.855207,1.334152,1.536656,0.015801,-4.611877,-0.486254,1.305912,1.039207,0.595318,1.621946,1.144756,0.316162,0.149745,0.520286,0.822524
2,10500,"Albany, GA (Metropolitan Statistical Area)",-1.167784,1.533074,-0.199280,2.625246,0.553775,0.659878,-0.603798,-2.416226,-1.170059,1.794506,0.251298,0.385449,1.107988,1.043722,0.363556,0.193357,0.682773,1.037231
3,10540,"Albany-Lebanon, OR (Metropolitan Statistical A...",-1.119655,-0.786907,1.837647,4.371355,1.881306,2.379561,-0.122594,-5.634490,-0.997826,-0.397754,0.605338,0.871111,2.686918,2.301023,1.125481,3.546706,2.662803,1.348113
4,10580,"Albany-Schenectady-Troy, NY (Metropolitan Stat...",-0.386304,0.713207,1.137991,1.285873,0.662660,1.244158,0.559249,-1.583846,-1.348554,0.652534,1.146290,1.028209,0.957357,1.443207,1.218819,1.217108,1.028761,0.584085
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,49420,"Yakima, WA (Metropolitan Statistical Area)",0.043484,1.290649,-0.845966,1.504995,2.481575,0.642729,2.687791,-1.408948,-0.736624,0.770632,4.003632,0.432529,1.529664,1.017242,1.555988,1.640110,1.686718,1.166081
380,49620,"York-Hanover, PA (Metropolitan Statistical Area)",-0.177766,0.246284,2.526718,2.987014,1.498067,2.183957,0.151862,-3.934661,-0.457831,1.229802,0.542460,0.587777,1.011599,0.946146,1.686409,0.881842,1.166493,1.105225
381,49660,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",-1.831271,-0.936645,-0.260418,0.568914,-0.232604,-0.456056,-1.817983,-5.096755,0.040232,1.510061,0.728197,0.069961,0.143303,0.007641,0.092034,-1.348707,0.189227,-0.404770
382,49700,"Yuba City, CA (Metropolitan Statistical Area)",1.471569,0.270816,2.117527,1.173746,2.349647,2.371273,-3.386678,-3.080590,-1.418976,0.059175,2.242540,2.343432,2.063698,2.737368,1.832617,2.124372,2.392559,3.399639
383,49740,"Yuma, AZ (Metropolitan Statistical Area)",3.011775,2.424984,5.324015,2.916529,3.672904,1.598310,-1.703578,-4.428375,-0.073787,1.360434,1.729886,0.826567,0.715060,2.553069,3.349650,-0.429664,1.791762,1.581085

In [4]:
predictions = []
for i in range(0,384):
    x = [[2002],[2003],[2004],[2005],[2006],[2007],[2008],[2009],[2010],[2011],[2012],[2013],[2014],[2015],[2016],[2017],[2018],[2019]]
    y = employment_df.iloc[i, 2:].values
    model.fit(x,y)
    y_pred = model.predict([[2020]])
    predictions.append(y_pred)
flat_list = [item for sublist in predictions for item in sublist]
employment_df[2020] = flat_list
employment_df

,GeoFips,GeoName,2002,2003,2004,2005,2006,2007,2008,2009,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,10180,"Abilene, TX (Metropolitan Statistical Area)",0.923909,0.878921,0.950270,1.020674,1.248157,2.536744,2.881307,-2.009792,...,1.429619,1.680364,1.358132,1.103766,0.288322,-0.009746,0.180310,1.702566,2.744509,1.108963
1,10420,"Akron, OH (Metropolitan Statistical Area)",-0.073308,-0.068572,2.068665,1.855207,1.334152,1.536656,0.015801,-4.611877,...,1.305912,1.039207,0.595318,1.621946,1.144756,0.316162,0.149745,0.520286,0.822524,0.531482
2,10500,"Albany, GA (Metropolitan Statistical Area)",-1.167784,1.533074,-0.199280,2.625246,0.553775,0.659878,-0.603798,-2.416226,...,1.794506,0.251298,0.385449,1.107988,1.043722,0.363556,0.193357,0.682773,1.037231,0.649406
3,10540,"Albany-Lebanon, OR (Metropolitan Statistical A...",-1.119655,-0.786907,1.837647,4.371355,1.881306,2.379561,-0.122594,-5.634490,...,-0.397754,0.605338,0.871111,2.686918,2.301023,1.125481,3.546706,2.662803,1.348113,2.002523
4,10580,"Albany-Schenectady-Troy, NY (Metropolitan Stat...",-0.386304,0.713207,1.137991,1.285873,0.662660,1.244158,0.559249,-1.583846,...,0.652534,1.146290,1.028209,0.957357,1.443207,1.218819,1.217108,1.028761,0.584085,1.025350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,49420,"Yakima, WA (Metropolitan Statistical Area)",0.043484,1.290649,-0.845966,1.504995,2.481575,0.642729,2.687791,-1.408948,...,0.770632,4.003632,0.432529,1.529664,1.017242,1.555988,1.640110,1.686718,1.166081,1.644016
380,49620,"York-Hanover, PA (Metropolitan Statistical Area)",-0.177766,0.246284,2.526718,2.987014,1.498067,2.183957,0.151862,-3.934661,...,1.229802,0.542460,0.587777,1.011599,0.946146,1.686409,0.881842,1.166493,1.105225,0.827549
381,49660,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",-1.831271,-0.936645,-0.260418,0.568914,-0.232604,-0.456056,-1.817983,-5.096755,...,1.510061,0.728197,0.069961,0.143303,0.007641,0.092034,-1.348707,0.189227,-0.404770,0.051817
382,49700,"Yuba City, CA (Metropolitan Statistical Area)",1.471569,0.270816,2.117527,1.173746,2.349647,2.371273,-3.386678,-3.080590,...,0.059175,2.242540,2.343432,2.063698,2.737368,1.832617,2.124372,2.392559,3.399639,2.340545
383,49740,"Yuma, AZ (Metropolitan Statistical Area)",3.011775,2.424984,5.324015,2.916529,3.672904,1.598310,-1.703578,-4.428375,...,1.360434,1.729886,0.826567,0.715060,2.553069,3.349650,-0.429664,1.791762,1.581085,0.598318

In [6]:
predictions = []
for i in range(0,384):
    x = [[2002],[2003],[2004],[2005],[2006],[2007],[2008],[2009],[2010],[2011],[2012],[2013],[2014],[2015],[2016],[2017],[2018],[2019],[2020]]
    y = employment_df.iloc[i, 2:].values
    model.fit(x,y)
    y_pred = model.predict([[2021]])
    predictions.append(y_pred)
flat_list = [item for sublist in predictions for item in sublist]
employment_df[2021] = flat_list
employment_df

,GeoFips,GeoName,2002,2003,2004,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,10180,"Abilene, TX (Metropolitan Statistical Area)",0.923909,0.878921,0.950270,1.020674,1.248157,2.536744,2.881307,-2.009792,...,1.680364,1.358132,1.103766,0.288322,-0.009746,0.180310,1.702566,2.744509,1.108963,1.117888
1,10420,"Akron, OH (Metropolitan Statistical Area)",-0.073308,-0.068572,2.068665,1.855207,1.334152,1.536656,0.015801,-4.611877,...,1.039207,0.595318,1.621946,1.144756,0.316162,0.149745,0.520286,0.822524,0.531482,0.534292
2,10500,"Albany, GA (Metropolitan Statistical Area)",-1.167784,1.533074,-0.199280,2.625246,0.553775,0.659878,-0.603798,-2.416226,...,0.251298,0.385449,1.107988,1.043722,0.363556,0.193357,0.682773,1.037231,0.649406,0.678731
3,10540,"Albany-Lebanon, OR (Metropolitan Statistical A...",-1.119655,-0.786907,1.837647,4.371355,1.881306,2.379561,-0.122594,-5.634490,...,0.605338,0.871111,2.686918,2.301023,1.125481,3.546706,2.662803,1.348113,2.002523,2.116484
4,10580,"Albany-Schenectady-Troy, NY (Metropolitan Stat...",-0.386304,0.713207,1.137991,1.285873,0.662660,1.244158,0.559249,-1.583846,...,1.146290,1.028209,0.957357,1.443207,1.218819,1.217108,1.028761,0.584085,1.025350,1.065675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,49420,"Yakima, WA (Metropolitan Statistical Area)",0.043484,1.290649,-0.845966,1.504995,2.481575,0.642729,2.687791,-1.408948,...,4.003632,0.432529,1.529664,1.017242,1.555988,1.640110,1.686718,1.166081,1.644016,1.703255
380,49620,"York-Hanover, PA (Metropolitan Statistical Area)",-0.177766,0.246284,2.526718,2.987014,1.498067,2.183957,0.151862,-3.934661,...,0.542460,0.587777,1.011599,0.946146,1.686409,0.881842,1.166493,1.105225,0.827549,0.831727
381,49660,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",-1.831271,-0.936645,-0.260418,0.568914,-0.232604,-0.456056,-1.817983,-5.096755,...,0.728197,0.069961,0.143303,0.007641,0.092034,-1.348707,0.189227,-0.404770,0.051817,0.110111
382,49700,"Yuba City, CA (Metropolitan Statistical Area)",1.471569,0.270816,2.117527,1.173746,2.349647,2.371273,-3.386678,-3.080590,...,2.242540,2.343432,2.063698,2.737368,1.832617,2.124372,2.392559,3.399639,2.340545,2.463739
383,49740,"Yuma, AZ (Metropolitan Statistical Area)",3.011775,2.424984,5.324015,2.916529,3.672904,1.598310,-1.703578,-4.428375,...,1.729886,0.826567,0.715060,2.553069,3.349650,-0.429664,1.791762,1.581085,0.598318,0.507962

In [7]:
predictions = []
for i in range(0,384):
    x = [[2002],[2003],[2004],[2005],[2006],[2007],[2008],[2009],[2010],[2011],[2012],[2013],[2014],[2015],[2016],[2017],[2018],[2019],[2020],[2021]]
    y = employment_df.iloc[i, 2:].values
    model.fit(x,y)
    y_pred = model.predict([[2022]])
    predictions.append(y_pred)
flat_list = [item for sublist in predictions for item in sublist]
employment_df[2022] = flat_list
employment_df

,GeoFips,GeoName,2002,2003,2004,2005,2006,2007,2008,2009,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,10180,"Abilene, TX (Metropolitan Statistical Area)",0.923909,0.878921,0.950270,1.020674,1.248157,2.536744,2.881307,-2.009792,...,1.358132,1.103766,0.288322,-0.009746,0.180310,1.702566,2.744509,1.108963,1.117888,1.126814
1,10420,"Akron, OH (Metropolitan Statistical Area)",-0.073308,-0.068572,2.068665,1.855207,1.334152,1.536656,0.015801,-4.611877,...,0.595318,1.621946,1.144756,0.316162,0.149745,0.520286,0.822524,0.531482,0.534292,0.537101
2,10500,"Albany, GA (Metropolitan Statistical Area)",-1.167784,1.533074,-0.199280,2.625246,0.553775,0.659878,-0.603798,-2.416226,...,0.385449,1.107988,1.043722,0.363556,0.193357,0.682773,1.037231,0.649406,0.678731,0.708057
3,10540,"Albany-Lebanon, OR (Metropolitan Statistical A...",-1.119655,-0.786907,1.837647,4.371355,1.881306,2.379561,-0.122594,-5.634490,...,0.871111,2.686918,2.301023,1.125481,3.546706,2.662803,1.348113,2.002523,2.116484,2.230444
4,10580,"Albany-Schenectady-Troy, NY (Metropolitan Stat...",-0.386304,0.713207,1.137991,1.285873,0.662660,1.244158,0.559249,-1.583846,...,1.028209,0.957357,1.443207,1.218819,1.217108,1.028761,0.584085,1.025350,1.065675,1.105999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,49420,"Yakima, WA (Metropolitan Statistical Area)",0.043484,1.290649,-0.845966,1.504995,2.481575,0.642729,2.687791,-1.408948,...,0.432529,1.529664,1.017242,1.555988,1.640110,1.686718,1.166081,1.644016,1.703255,1.762495
380,49620,"York-Hanover, PA (Metropolitan Statistical Area)",-0.177766,0.246284,2.526718,2.987014,1.498067,2.183957,0.151862,-3.934661,...,0.587777,1.011599,0.946146,1.686409,0.881842,1.166493,1.105225,0.827549,0.831727,0.835905
381,49660,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",-1.831271,-0.936645,-0.260418,0.568914,-0.232604,-0.456056,-1.817983,-5.096755,...,0.069961,0.143303,0.007641,0.092034,-1.348707,0.189227,-0.404770,0.051817,0.110111,0.168406
382,49700,"Yuba City, CA (Metropolitan Statistical Area)",1.471569,0.270816,2.117527,1.173746,2.349647,2.371273,-3.386678,-3.080590,...,2.343432,2.063698,2.737368,1.832617,2.124372,2.392559,3.399639,2.340545,2.463739,2.586932
383,49740,"Yuma, AZ (Metropolitan Statistical Area)",3.011775,2.424984,5.324015,2.916529,3.672904,1.598310,-1.703578,-4.428375,...,0.826567,0.715060,2.553069,3.349650,-0.429664,1.791762,1.581085,0.598318,0.507962,0.417606

In [8]:
predictions = []
for i in range(0,384):
    x = [[2002],[2003],[2004],[2005],[2006],[2007],[2008],[2009],[2010],[2011],[2012],[2013],[2014],[2015],[2016],[2017],[2018],[2019],[2020],[2021],[2022]]
    y = employment_df.iloc[i, 2:].values
    model.fit(x,y)
    y_pred = model.predict([[2023]])
    predictions.append(y_pred)
flat_list = [item for sublist in predictions for item in sublist]
employment_df[2023] = flat_list
employment_df

,GeoFips,GeoName,2002,2003,2004,2005,2006,2007,2008,2009,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,10180,"Abilene, TX (Metropolitan Statistical Area)",0.923909,0.878921,0.950270,1.020674,1.248157,2.536744,2.881307,-2.009792,...,1.103766,0.288322,-0.009746,0.180310,1.702566,2.744509,1.108963,1.117888,1.126814,1.135739
1,10420,"Akron, OH (Metropolitan Statistical Area)",-0.073308,-0.068572,2.068665,1.855207,1.334152,1.536656,0.015801,-4.611877,...,1.621946,1.144756,0.316162,0.149745,0.520286,0.822524,0.531482,0.534292,0.537101,0.539910
2,10500,"Albany, GA (Metropolitan Statistical Area)",-1.167784,1.533074,-0.199280,2.625246,0.553775,0.659878,-0.603798,-2.416226,...,1.107988,1.043722,0.363556,0.193357,0.682773,1.037231,0.649406,0.678731,0.708057,0.737382
3,10540,"Albany-Lebanon, OR (Metropolitan Statistical A...",-1.119655,-0.786907,1.837647,4.371355,1.881306,2.379561,-0.122594,-5.634490,...,2.686918,2.301023,1.125481,3.546706,2.662803,1.348113,2.002523,2.116484,2.230444,2.344405
4,10580,"Albany-Schenectady-Troy, NY (Metropolitan Stat...",-0.386304,0.713207,1.137991,1.285873,0.662660,1.244158,0.559249,-1.583846,...,0.957357,1.443207,1.218819,1.217108,1.028761,0.584085,1.025350,1.065675,1.105999,1.146324
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,49420,"Yakima, WA (Metropolitan Statistical Area)",0.043484,1.290649,-0.845966,1.504995,2.481575,0.642729,2.687791,-1.408948,...,1.529664,1.017242,1.555988,1.640110,1.686718,1.166081,1.644016,1.703255,1.762495,1.821735
380,49620,"York-Hanover, PA (Metropolitan Statistical Area)",-0.177766,0.246284,2.526718,2.987014,1.498067,2.183957,0.151862,-3.934661,...,1.011599,0.946146,1.686409,0.881842,1.166493,1.105225,0.827549,0.831727,0.835905,0.840084
381,49660,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",-1.831271,-0.936645,-0.260418,0.568914,-0.232604,-0.456056,-1.817983,-5.096755,...,0.143303,0.007641,0.092034,-1.348707,0.189227,-0.404770,0.051817,0.110111,0.168406,0.226700
382,49700,"Yuba City, CA (Metropolitan Statistical Area)",1.471569,0.270816,2.117527,1.173746,2.349647,2.371273,-3.386678,-3.080590,...,2.063698,2.737368,1.832617,2.124372,2.392559,3.399639,2.340545,2.463739,2.586932,2.710126
383,49740,"Yuma, AZ (Metropolitan Statistical Area)",3.011775,2.424984,5.324015,2.916529,3.672904,1.598310,-1.703578,-4.428375,...,0.715060,2.553069,3.349650,-0.429664,1.791762,1.581085,0.598318,0.507962,0.417606,0.327250

In [9]:
predictions = []
for i in range(0,384):
    x = [[2002],[2003],[2004],[2005],[2006],[2007],[2008],[2009],[2010],[2011],[2012],[2013],[2014],[2015],[2016],[2017],[2018],[2019],[2020],[2021],[2022],[2023]]
    y = employment_df.iloc[i, 2:].values
    model.fit(x,y)
    y_pred = model.predict([[2024]])
    predictions.append(y_pred)
flat_list = [item for sublist in predictions for item in sublist]
employment_df[2024] = flat_list
employment_df

,GeoFips,GeoName,2002,2003,2004,2005,2006,2007,2008,2009,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,10180,"Abilene, TX (Metropolitan Statistical Area)",0.923909,0.878921,0.950270,1.020674,1.248157,2.536744,2.881307,-2.009792,...,0.288322,-0.009746,0.180310,1.702566,2.744509,1.108963,1.117888,1.126814,1.135739,1.144664
1,10420,"Akron, OH (Metropolitan Statistical Area)",-0.073308,-0.068572,2.068665,1.855207,1.334152,1.536656,0.015801,-4.611877,...,1.144756,0.316162,0.149745,0.520286,0.822524,0.531482,0.534292,0.537101,0.539910,0.542719
2,10500,"Albany, GA (Metropolitan Statistical Area)",-1.167784,1.533074,-0.199280,2.625246,0.553775,0.659878,-0.603798,-2.416226,...,1.043722,0.363556,0.193357,0.682773,1.037231,0.649406,0.678731,0.708057,0.737382,0.766707
3,10540,"Albany-Lebanon, OR (Metropolitan Statistical A...",-1.119655,-0.786907,1.837647,4.371355,1.881306,2.379561,-0.122594,-5.634490,...,2.301023,1.125481,3.546706,2.662803,1.348113,2.002523,2.116484,2.230444,2.344405,2.458366
4,10580,"Albany-Schenectady-Troy, NY (Metropolitan Stat...",-0.386304,0.713207,1.137991,1.285873,0.662660,1.244158,0.559249,-1.583846,...,1.443207,1.218819,1.217108,1.028761,0.584085,1.025350,1.065675,1.105999,1.146324,1.186648
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,49420,"Yakima, WA (Metropolitan Statistical Area)",0.043484,1.290649,-0.845966,1.504995,2.481575,0.642729,2.687791,-1.408948,...,1.017242,1.555988,1.640110,1.686718,1.166081,1.644016,1.703255,1.762495,1.821735,1.880975
380,49620,"York-Hanover, PA (Metropolitan Statistical Area)",-0.177766,0.246284,2.526718,2.987014,1.498067,2.183957,0.151862,-3.934661,...,0.946146,1.686409,0.881842,1.166493,1.105225,0.827549,0.831727,0.835905,0.840084,0.844262
381,49660,"Youngstown-Warren-Boardman, OH-PA (Metropolita...",-1.831271,-0.936645,-0.260418,0.568914,-0.232604,-0.456056,-1.817983,-5.096755,...,0.007641,0.092034,-1.348707,0.189227,-0.404770,0.051817,0.110111,0.168406,0.226700,0.284994
382,49700,"Yuba City, CA (Metropolitan Statistical Area)",1.471569,0.270816,2.117527,1.173746,2.349647,2.371273,-3.386678,-3.080590,...,2.737368,1.832617,2.124372,2.392559,3.399639,2.340545,2.463739,2.586932,2.710126,2.833319
383,49740,"Yuma, AZ (Metropolitan Statistical Area)",3.011775,2.424984,5.324015,2.916529,3.672904,1.598310,-1.703578,-4.428375,...,2.553069,3.349650,-0.429664,1.791762,1.581085,0.598318,0.507962,0.417606,0.327250,0.236894

In [13]:
employment_df.rename(columns = {2020:'prediction_2020',2021:'prediction_2021',2022:'prediction_2022',2023:'prediction_2023',2024:'prediction_2024'}, inplace = True)
employment_df

         2020      2021      2022      2023      2024
0    1.108963  1.117888  1.126814  1.135739  1.144664
1    0.531482  0.534292  0.537101  0.539910  0.542719
2    0.649406  0.678731  0.708057  0.737382  0.766707
3    2.002523  2.116484  2.230444  2.344405  2.458366
4    1.025350  1.065675  1.105999  1.146324  1.186648
..        ...       ...       ...       ...       ...
379  1.644016  1.703255  1.762495  1.821735  1.880975
380  0.827549  0.831727  0.835905  0.840084  0.844262
381  0.051817  0.110111  0.168406  0.226700  0.284994
382  2.340545  2.463739  2.586932  2.710126  2.833319
383  0.598318  0.507962  0.417606  0.327250  0.236894

[384 rows x 5 columns]

In [10]:
employment_df.to_csv('employment_prediction_multiyear.csv')